from __future__ import annotations

import asyncio
import json
import shutil
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from golem.config import GolemConfig, load_config, save_config
from golem.executor import execute_all_groups, run_final_validation
from golem.planner import run_planner
from golem.progress import ProgressLogger
from golem.tasks import TasksFile, read_tasks, write_tasks
from golem.tui import LiveDashboard, PreRunScreen, force_defaults
from golem.worktree import create_pr, merge_group_branches

app = typer.Typer(name="golem", help="Autonomous spec executor with parallel workers and validators.")
console = Console()

_GOLEM_DIR_NAME = ".golem"


def _get_golem_dir(project_root: Path) -> Path:
    return project_root / _GOLEM_DIR_NAME


def _get_project_root() -> Path:
    return Path.cwd()


@app.command()
def run(
    spec: Path = typer.Argument(..., help="Path to spec markdown file"),
    force: bool = typer.Option(False, "--force", help="Skip TUI, use defaults (for CI/non-interactive)"),
) -> None:
    """Full autonomous run: plan, execute, validate, create PR."""
    project_root = _get_project_root()
    golem_dir = _get_golem_dir(project_root)
    golem_dir.mkdir(parents=True, exist_ok=True)

    config = load_config(golem_dir)
    save_config(config, golem_dir)
    progress = ProgressLogger(golem_dir)

    async def _run_async() -> None:
        nonlocal config

        # Plan phase
        console.print("[bold cyan]Golem[/bold cyan] — Planning...")
        tasks_file = await run_planner(spec, golem_dir, config, project_root)
        console.print(f"  Found {sum(len(g.tasks) for g in tasks_file.groups)} tasks across {len(tasks_file.groups)} groups")

        if not force:
            groups_summary = [
                f"Group {g.id} ({len(g.tasks)} tasks): {g.description}"
                for g in tasks_file.groups
            ]
            pre_run = PreRunScreen(
                group_count=len(tasks_file.groups),
                task_count=sum(len(g.tasks) for g in tasks_file.groups),
                groups_summary=groups_summary,
            )
            config, action = pre_run.run(config)
            if action == "quit":
                raise typer.Exit(0)
            if action == "dry_run":
                console.print(json.dumps(tasks_file.to_dict(), indent=2))
                raise typer.Exit(0)
            save_config(config, golem_dir)

        # Execute phase
        task_counts = {g.id: len(g.tasks) for g in tasks_file.groups}
        group_ids = [g.id for g in tasks_file.groups]

        if force:
            await execute_all_groups(tasks_file, golem_dir, project_root, config, progress)
        else:
            with LiveDashboard(group_ids, task_counts) as dashboard:
                await execute_all_groups(
                    tasks_file, golem_dir, project_root, config, progress,
                    dashboard_cb=dashboard.get_callback(),
                )

        # Merge phase
        spec_slug = spec.stem.lower().replace("_", "-").replace(" ", "-")
        target_branch = f"golem/{spec_slug}"
        group_branches = [g.worktree_branch for g in tasks_file.groups]
        merge_ok, conflict_info = merge_group_branches(group_branches, target_branch, project_root)

        # Final validation
        merged_path = project_root  # run final validation in project root after merge
        final_ok, final_results = run_final_validation(tasks_file, merged_path)
        progress.log_final_validation(final_ok)

        # Build PR body
        completed = [t for g in tasks_file.groups for t in g.tasks if t.status == "completed"]
        blocked = [t for g in tasks_file.groups for t in g.tasks if t.status == "blocked"]

        pr_body = f"## Golem Run Report\n\n**Spec:** `{spec}`\n"
        pr_body += f"**Tasks:** {len(completed)}/{len(completed)+len(blocked)} completed, {len(blocked)} blocked\n\n"
        pr_body += "### Completed Tasks\n"
        for t in completed:
            pr_body += f"- [x] {t.id}: {t.description[:80]}\n"
        if blocked:
            pr_body += "\n### Blocked Tasks\n"
            for t in blocked:
                pr_body += f"- [ ] {t.id}: {t.description[:80]}\n"
                if t.last_feedback:
                    pr_body += f"  - Last feedback: {t.last_feedback[:200]}\n"
        pr_body += "\n### Validation\n"
        for line in final_results:
            pr_body += f"- {line}\n"
        pr_body += "\nGenerated by Golem"

        if config.auto_pr:
            try:
                pr_url = create_pr(target_branch, f"golem: {spec.stem}", pr_body, not final_ok, project_root, config.pr_target)
                console.print(f"\n[bold green]PR created:[/bold green] {pr_url}")
            except RuntimeError as e:
                console.print(f"\n[yellow]Could not create PR:[/yellow] {e}")

        if conflict_info:
            console.print(f"\n[yellow]Merge conflicts:[/yellow] {conflict_info}")

        console.print(f"\n[bold]Done.[/bold] {len(completed)} completed, {len(blocked)} blocked.")

    asyncio.run(_run_async())


@app.command()
def plan(
    spec: Path = typer.Argument(..., help="Path to spec markdown file"),
) -> None:
    """Generate tasks.json only (dry run — no workers executed)."""
    project_root = _get_project_root()
    golem_dir = _get_golem_dir(project_root)
    golem_dir.mkdir(parents=True, exist_ok=True)

    config = load_config(golem_dir)

    async def _plan_async() -> None:
        console.print("[bold cyan]Golem[/bold cyan] — Planning (dry run)...")
        tasks_file = await run_planner(spec, golem_dir, config, project_root)
        tasks_path = golem_dir / "tasks.json"
        console.print(f"[bold green]tasks.json written to:[/bold green] {tasks_path}")
        console.print(f"Groups: {len(tasks_file.groups)}, Tasks: {sum(len(g.tasks) for g in tasks_file.groups)}")

    asyncio.run(_plan_async())


@app.command()
def status() -> None:
    """Show current run progress from tasks.json."""
    project_root = _get_project_root()
    golem_dir = _get_golem_dir(project_root)
    tasks_path = golem_dir / "tasks.json"

    if not tasks_path.exists():
        console.print("[red]No tasks.json found. Run 'golem plan <spec>' first.[/red]")
        raise typer.Exit(1)

    tasks_file = read_tasks(tasks_path)

    table = Table(title="Golem Status", show_header=True)
    table.add_column("Task ID", style="cyan")
    table.add_column("Group")
    table.add_column("Status")
    table.add_column("Retries")
    table.add_column("Description")

    for group in tasks_file.groups:
        for task in group.tasks:
            status_style = {
                "completed": "[green]completed[/green]",
                "blocked": "[red]blocked[/red]",
                "in_progress": "[yellow]in_progress[/yellow]",
                "pending": "pending",
            }.get(task.status, task.status)
            table.add_row(task.id, group.id, status_style, str(task.retries), task.description[:60])

    console.print(table)


@app.command()
def resume() -> None:
    """Resume interrupted run from tasks.json."""
    project_root = _get_project_root()
    golem_dir = _get_golem_dir(project_root)
    tasks_path = golem_dir / "tasks.json"

    if not tasks_path.exists():
        console.print("[red]No tasks.json found.[/red]")
        raise typer.Exit(1)

    tasks_file = read_tasks(tasks_path)

    # Reset in_progress → pending
    for group in tasks_file.groups:
        for task in group.tasks:
            if task.status == "in_progress":
                task.status = "pending"

    async def _resume_async() -> None:
        await write_tasks(tasks_file, tasks_path)
        config = load_config(golem_dir)
        progress = ProgressLogger(golem_dir)
        console.print("[bold cyan]Golem[/bold cyan] — Resuming...")
        await execute_all_groups(tasks_file, golem_dir, project_root, config, progress)
        console.print("[bold]Resume complete.[/bold]")

    asyncio.run(_resume_async())


@app.command()
def version() -> None:
    """Show Golem version, Python version, and platform."""
    from golem.version import get_version_info

    info = get_version_info()
    console.print(f"[bold cyan]Golem[/bold cyan] v{info['version']}")
    console.print(f"Python {info['python']}")
    console.print(f"Platform {info['platform']}")


@app.command()
def clean() -> None:
    """Remove .golem/ state, worktrees, and branches."""
    project_root = _get_project_root()
    golem_dir = _get_golem_dir(project_root)

    if not golem_dir.exists():
        console.print("[yellow].golem/ does not exist — nothing to clean.[/yellow]")
        return

    # Remove worktrees via git
    worktrees_dir = golem_dir / "worktrees"
    if worktrees_dir.exists():
        for wt in worktrees_dir.iterdir():
            if wt.is_dir():
                import subprocess
                subprocess.run(["git", "worktree", "remove", "--force", str(wt)], cwd=project_root, capture_output=True)

    shutil.rmtree(golem_dir, ignore_errors=True)
    console.print("[bold green]Cleaned .golem/ directory.[/bold green]")
